<?php
/**
 * FullEmailValidationResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FullEmailValidationResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Full email addresss validation result
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FullEmailValidationResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FullEmailValidationResponse"
     */
    public function testFullEmailValidationResponse()
    {
    }

    /**
     * Test attribute "valid_address"
     */
    public function testPropertyValidAddress()
    {
    }

    /**
     * Test attribute "mail_server_used_for_validation"
     */
    public function testPropertyMailServerUsedForValidation()
    {
    }

    /**
     * Test attribute "valid_syntax"
     */
    public function testPropertyValidSyntax()
    {
    }

    /**
     * Test attribute "valid_domain"
     */
    public function testPropertyValidDomain()
    {
    }

    /**
     * Test attribute "valid_smtp"
     */
    public function testPropertyValidSmtp()
    {
    }

    /**
     * Test attribute "is_catchall_domain"
     */
    public function testPropertyIsCatchallDomain()
    {
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
    }

    /**
     * Test attribute "is_free_email_provider"
     */
    public function testPropertyIsFreeEmailProvider()
    {
    }

    /**
     * Test attribute "is_disposable"
     */
    public function testPropertyIsDisposable()
    {
    }
}
