<?php
/**
 * IPIntelligenceResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IPIntelligenceResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description IP address intelligence result
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IPIntelligenceResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IPIntelligenceResponse"
     */
    public function testIPIntelligenceResponse()
    {
    }

    /**
     * Test attribute "is_bot"
     */
    public function testPropertyIsBot()
    {
    }

    /**
     * Test attribute "is_tor_node"
     */
    public function testPropertyIsTorNode()
    {
    }

    /**
     * Test attribute "is_threat"
     */
    public function testPropertyIsThreat()
    {
    }

    /**
     * Test attribute "is_eu"
     */
    public function testPropertyIsEu()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "currency_name"
     */
    public function testPropertyCurrencyName()
    {
    }

    /**
     * Test attribute "region_area"
     */
    public function testPropertyRegionArea()
    {
    }

    /**
     * Test attribute "subregion_area"
     */
    public function testPropertySubregionArea()
    {
    }
}
