<?php
/**
 * LeadEnrichmentResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LeadEnrichmentResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Result of the lead enrichment process
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LeadEnrichmentResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LeadEnrichmentResponse"
     */
    public function testLeadEnrichmentResponse()
    {
    }

    /**
     * Test attribute "successful"
     */
    public function testPropertySuccessful()
    {
    }

    /**
     * Test attribute "lead_type"
     */
    public function testPropertyLeadType()
    {
    }

    /**
     * Test attribute "contact_business_email"
     */
    public function testPropertyContactBusinessEmail()
    {
    }

    /**
     * Test attribute "contact_first_name"
     */
    public function testPropertyContactFirstName()
    {
    }

    /**
     * Test attribute "contact_last_name"
     */
    public function testPropertyContactLastName()
    {
    }

    /**
     * Test attribute "contact_gender"
     */
    public function testPropertyContactGender()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "company_domain_name"
     */
    public function testPropertyCompanyDomainName()
    {
    }

    /**
     * Test attribute "company_house_number"
     */
    public function testPropertyCompanyHouseNumber()
    {
    }

    /**
     * Test attribute "company_street"
     */
    public function testPropertyCompanyStreet()
    {
    }

    /**
     * Test attribute "company_city"
     */
    public function testPropertyCompanyCity()
    {
    }

    /**
     * Test attribute "company_state_or_province"
     */
    public function testPropertyCompanyStateOrProvince()
    {
    }

    /**
     * Test attribute "company_postal_code"
     */
    public function testPropertyCompanyPostalCode()
    {
    }

    /**
     * Test attribute "company_country"
     */
    public function testPropertyCompanyCountry()
    {
    }

    /**
     * Test attribute "company_country_code"
     */
    public function testPropertyCompanyCountryCode()
    {
    }

    /**
     * Test attribute "company_telephone"
     */
    public function testPropertyCompanyTelephone()
    {
    }

    /**
     * Test attribute "company_vat_number"
     */
    public function testPropertyCompanyVatNumber()
    {
    }

    /**
     * Test attribute "employee_count"
     */
    public function testPropertyEmployeeCount()
    {
    }
}
