<?php
/**
 * PublicHolidayOccurrenceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PublicHolidayOccurrenceTest Class Doc Comment
 *
 * @category    Class */
// * @description Public holiday occurrence
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PublicHolidayOccurrenceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PublicHolidayOccurrence"
     */
    public function testPublicHolidayOccurrence()
    {
    }

    /**
     * Test attribute "english_name"
     */
    public function testPropertyEnglishName()
    {
    }

    /**
     * Test attribute "local_name"
     */
    public function testPropertyLocalName()
    {
    }

    /**
     * Test attribute "occurrence_date"
     */
    public function testPropertyOccurrenceDate()
    {
    }

    /**
     * Test attribute "holiday_type"
     */
    public function testPropertyHolidayType()
    {
    }

    /**
     * Test attribute "nationwaide"
     */
    public function testPropertyNationwaide()
    {
    }
}
