<?php
/**
 * ValidateIdentifierRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ValidateIdentifierRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description Identifier validation request, including the input identifier as well as various identifier rules
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ValidateIdentifierRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ValidateIdentifierRequest"
     */
    public function testValidateIdentifierRequest()
    {
    }

    /**
     * Test attribute "input"
     */
    public function testPropertyInput()
    {
    }

    /**
     * Test attribute "allow_whitespace"
     */
    public function testPropertyAllowWhitespace()
    {
    }

    /**
     * Test attribute "allow_hyphens"
     */
    public function testPropertyAllowHyphens()
    {
    }

    /**
     * Test attribute "allow_underscore"
     */
    public function testPropertyAllowUnderscore()
    {
    }

    /**
     * Test attribute "allow_numbers"
     */
    public function testPropertyAllowNumbers()
    {
    }

    /**
     * Test attribute "allow_periods"
     */
    public function testPropertyAllowPeriods()
    {
    }

    /**
     * Test attribute "max_length"
     */
    public function testPropertyMaxLength()
    {
    }

    /**
     * Test attribute "min_length"
     */
    public function testPropertyMinLength()
    {
    }
}
