<?php
/**
 * ValidateUrlResponseFullTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ValidateUrlResponseFullTest Class Doc Comment
 *
 * @category    Class */
// * @description Result of validating a URL with full validation
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ValidateUrlResponseFullTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ValidateUrlResponseFull"
     */
    public function testValidateUrlResponseFull()
    {
    }

    /**
     * Test attribute "valid_url"
     */
    public function testPropertyValidUrl()
    {
    }

    /**
     * Test attribute "valid_syntax"
     */
    public function testPropertyValidSyntax()
    {
    }

    /**
     * Test attribute "valid_domain"
     */
    public function testPropertyValidDomain()
    {
    }

    /**
     * Test attribute "valid_endpoint"
     */
    public function testPropertyValidEndpoint()
    {
    }

    /**
     * Test attribute "well_formed_url"
     */
    public function testPropertyWellFormedUrl()
    {
    }
}
