<?php
/**
 * ValidateCountryResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ValidateCountryResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Result of performing a country validation operation
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ValidateCountryResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ValidateCountryResponse"
     */
    public function testValidateCountryResponse()
    {
    }

    /**
     * Test attribute "successful"
     */
    public function testPropertySuccessful()
    {
    }

    /**
     * Test attribute "country_full_name"
     */
    public function testPropertyCountryFullName()
    {
    }

    /**
     * Test attribute "iso_two_letter_code"
     */
    public function testPropertyIsoTwoLetterCode()
    {
    }

    /**
     * Test attribute "fips_two_letter_code"
     */
    public function testPropertyFipsTwoLetterCode()
    {
    }

    /**
     * Test attribute "three_letter_code"
     */
    public function testPropertyThreeLetterCode()
    {
    }

    /**
     * Test attribute "is_european_union_member"
     */
    public function testPropertyIsEuropeanUnionMember()
    {
    }

    /**
     * Test attribute "timezones"
     */
    public function testPropertyTimezones()
    {
    }

    /**
     * Test attribute "iso_currency_code"
     */
    public function testPropertyIsoCurrencyCode()
    {
    }

    /**
     * Test attribute "currency_symbol"
     */
    public function testPropertyCurrencySymbol()
    {
    }

    /**
     * Test attribute "currency_english_name"
     */
    public function testPropertyCurrencyEnglishName()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "subregion"
     */
    public function testPropertySubregion()
    {
    }
}
