<?php
/**
 * WhoisResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WhoisResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Result of a WHOIS operation
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WhoisResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WhoisResponse"
     */
    public function testWhoisResponse()
    {
    }

    /**
     * Test attribute "valid_domain"
     */
    public function testPropertyValidDomain()
    {
    }

    /**
     * Test attribute "whois_server"
     */
    public function testPropertyWhoisServer()
    {
    }

    /**
     * Test attribute "raw_text_record"
     */
    public function testPropertyRawTextRecord()
    {
    }

    /**
     * Test attribute "created_dt"
     */
    public function testPropertyCreatedDt()
    {
    }
}
