<?php
/**
 * AddressApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AddressApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddressApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addressCheckEUMembership
     *
     * Check if a country is a member of the European Union (EU).
     *
     */
    public function testAddressCheckEUMembership()
    {
    }

    /**
     * Test case for addressCountry
     *
     * Validate and normalize country information, return ISO 3166-1 country codes and country name.
     *
     */
    public function testAddressCountry()
    {
    }

    /**
     * Test case for addressCountryList
     *
     * Get a list of ISO 3166-1 countries.
     *
     */
    public function testAddressCountryList()
    {
    }

    /**
     * Test case for addressGeocode
     *
     * Geocode a street address into latitude and longitude.
     *
     */
    public function testAddressGeocode()
    {
    }

    /**
     * Test case for addressGetCountryCurrency
     *
     * Get the currency of the input country.
     *
     */
    public function testAddressGetCountryCurrency()
    {
    }

    /**
     * Test case for addressGetCountryRegion
     *
     * Get the region, subregion and continent of the country.
     *
     */
    public function testAddressGetCountryRegion()
    {
    }

    /**
     * Test case for addressGetTimezone
     *
     * Gets IANA/Olsen time zones for a country.
     *
     */
    public function testAddressGetTimezone()
    {
    }

    /**
     * Test case for addressNormalizeAddress
     *
     * Normalize a street address.
     *
     */
    public function testAddressNormalizeAddress()
    {
    }

    /**
     * Test case for addressParseString
     *
     * Parse an unstructured input text string into an international, formatted address.
     *
     */
    public function testAddressParseString()
    {
    }

    /**
     * Test case for addressReverseGeocodeAddress
     *
     * Reverse geocode a lattitude and longitude into an address.
     *
     */
    public function testAddressReverseGeocodeAddress()
    {
    }

    /**
     * Test case for addressValidateAddress
     *
     * Validate a street address.
     *
     */
    public function testAddressValidateAddress()
    {
    }

    /**
     * Test case for addressValidateCity
     *
     * Validate a City and State/Province combination, get location information about it.
     *
     */
    public function testAddressValidateCity()
    {
    }

    /**
     * Test case for addressValidatePostalCode
     *
     * Validate a postal code, get location information about it.
     *
     */
    public function testAddressValidatePostalCode()
    {
    }

    /**
     * Test case for addressValidateState
     *
     * Validate a state or province, name or abbreviation, get location information about it.
     *
     */
    public function testAddressValidateState()
    {
    }
}
