<?php
/**
 * DateTimeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DateTimeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DateTimeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for dateTimeGetNowSimple
     *
     * Get current date and time as of now.
     *
     */
    public function testDateTimeGetNowSimple()
    {
    }

    /**
     * Test case for dateTimeGetPublicHolidays
     *
     * Get public holidays in the specified country and year.
     *
     */
    public function testDateTimeGetPublicHolidays()
    {
    }

    /**
     * Test case for dateTimeParseNaturalLanguageDateTime
     *
     * Parses a free-form natural language date and time string into a date and time.
     *
     */
    public function testDateTimeParseNaturalLanguageDateTime()
    {
    }

    /**
     * Test case for dateTimeParseStandardDateTime
     *
     * Parses a standardized date and time string into a date and time.
     *
     */
    public function testDateTimeParseStandardDateTime()
    {
    }
}
