<?php
/**
 * DomainApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * validateapi
 *
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DomainApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DomainApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for domainCheck
     *
     * Validate a domain name.
     *
     */
    public function testDomainCheck()
    {
    }

    /**
     * Test case for domainGetTopLevelDomainFromUrl
     *
     * Get top-level domain name from URL.
     *
     */
    public function testDomainGetTopLevelDomainFromUrl()
    {
    }

    /**
     * Test case for domainIsAdminPath
     *
     * Check if path is a high-risk or vulnerable server administration path.
     *
     */
    public function testDomainIsAdminPath()
    {
    }

    /**
     * Test case for domainPhishingCheck
     *
     * Check a URL for Phishing threats.
     *
     */
    public function testDomainPhishingCheck()
    {
    }

    /**
     * Test case for domainPost
     *
     * Get WHOIS information for a domain.
     *
     */
    public function testDomainPost()
    {
    }

    /**
     * Test case for domainQualityScore
     *
     * Validate a domain name's quality score.
     *
     */
    public function testDomainQualityScore()
    {
    }

    /**
     * Test case for domainSafetyCheck
     *
     * Check a URL for safety threats.
     *
     */
    public function testDomainSafetyCheck()
    {
    }

    /**
     * Test case for domainSsrfCheck
     *
     * Check a URL for SSRF threats.
     *
     */
    public function testDomainSsrfCheck()
    {
    }

    /**
     * Test case for domainSsrfCheckBatch
     *
     * Check a URL for SSRF threats in batches.
     *
     */
    public function testDomainSsrfCheckBatch()
    {
    }

    /**
     * Test case for domainUrlFull
     *
     * Validate a URL fully.
     *
     */
    public function testDomainUrlFull()
    {
    }

    /**
     * Test case for domainUrlHtmlSsrfCheck
     *
     * Check a URL for HTML embedded SSRF threats.
     *
     */
    public function testDomainUrlHtmlSsrfCheck()
    {
    }

    /**
     * Test case for domainUrlSyntaxOnly
     *
     * Validate a URL syntactically.
     *
     */
    public function testDomainUrlSyntaxOnly()
    {
    }
}
